version: '3'

services:
  pinto-express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Bangkok
    image: nodejs
    container_name: pinto-express-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    command: nodemon --watch . --exec "node" index.js
    volumes:
    - "../storage:/storage"

networks:
  default:
    external:
      name: default-net
